# Generated by Django 6.0.4 on 2026-04-09 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(unique=True)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_dept', models.CharField(choices=[('it', 'IT'), ('hr', 'HR'), ('manager', 'MANAGER'), ('sales', 'SALES')], max_length=20)),
                ('emp_mobile', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('[6-9][0-9]{9}', message='Valid number starts from 6-9')])),
                ('emp_salary', models.FloatField()),
            ],
        ),
    ]
